USE [LoZUTracker]
GO

/****** Object:  Table [dbo].[Completes]    Script Date: 1/21/2022 12:01:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Completes](
	[UserID] [int] NOT NULL,
	[QuestID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[QuestID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Completes]  WITH CHECK ADD FOREIGN KEY([QuestID])
REFERENCES [dbo].[Quest] ([ID])
GO

ALTER TABLE [dbo].[Completes]  WITH CHECK ADD FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([ID])
GO

